function [x_dec, err_bits, total_bits] = afdm_rx_engine(r_signal, config, x_ref)
%AFDM_RX_ENGINE Run the AFDM receiver chain and compute bit errors.
%   [x_dec, err_bits, total_bits] = afdm_rx_engine(r_signal, config, x_ref)

    r_data = remove_cpp(r_signal, config.waveform.CPPLength);

    y_daft = daft_demod( ...
        r_data, ...
        config.waveform.NumSubcarriers, ...
        config.waveform.c1, ...
        config.waveform.c2);

    H_eff = estimate_effective_channel( ...
        config.waveform.NumSubcarriers, ...
        config.waveform.c1, ...
        config.waveform.c2, ...
        config.channel.chan_coef, ...
        config.channel.delay_taps, ...
        config.channel.doppler_freq);

    if ~isfield(config.channel, 'snr_db') || isempty(config.channel.snr_db)
        error('config.channel.snr_db must be defined.');
    end

    noise_var = 1 / (10^(config.channel.snr_db / 10));
    x_est = mmse_equalize(y_daft, H_eff, noise_var);
    x_dec = symbol_decision(x_est, config.modulation.M_mod, config.modulation.modType);
    [err_bits, total_bits] = compute_bit_errors(x_dec, x_ref);
end
